### PR TITLE
Update CI to Julia v1.10

### PR DESCRIPTION
**Pull request by patrickersing**

### CODE REVIEW

**Comment by patrickersing** [comment]
I have adjusted the tolerances, such that all tests pass again. As the errors in the well-balanced tests are close to machine precision, I had to set the relative tolerance to `rtol=10`, while the absolute tolerance remains at a reasonable level `atol=1e-10`.
An alternative would be to reset the expected values, but then we will probably run into the same problem with the next version update.

**Comment by andrewwinters5000** [comment]
Wouldn't it be enough to only adjust the absolute tolerances only on the well-balancing tests? The relative tolerances in the `isapprox` function do not hit a relative error. They are present to adjust for scaling. Instead, the function given two value `x` and `y` computes `max( atol , rtol * max( abs(x), abs(y) ) )`. For the well-balancedness tests the value of `rtol * max( abs(x), abs(y) )` should be very small. I took the values from a failing test [here](https://github.com/trixi-framework/TrixiShallowWater.jl/actions/runs/8229195887/job/22499931847#step:7:6188) to illustrate this:

```julia
julia> val1 = 4.998482888288039e-11
4.998482888288039e-11

julia> val2 = 4.704673109537872e-11
4.704673109537872e-11

julia> abs(val1-val2)
2.938097787501668e-12

julia> 1.4901161193847656e-8 * max( abs(val1), abs(val2) )
7.448319924306928e-19

julia> isapprox(val1, val2; atol = 1e-11)
true
```

**Review by andrewwinters5000 — APPROVED** [review]
LGTM! I would say we wait for #28 to get merged and then we can update the testing

**Comment by patrickersing** [comment]
> LGTM! I would say we wait for #28 to get merged and then we can update the testing

Sounds good!
Yes you are right, it works fine by just setting the `atol`. I falsely assumed `isapprox` was also comparing the relative error.

**Review by andrewwinters5000 — APPROVED** [review]

**Pull request merged**
