### PR TITLE
Remove `normal_direction_ll`

### PR DESCRIPTION
**Pull request by patrickersing**
This PR removes `normal_direction_ll` from the function signature of the nonconservative terms, to account for the changes in https://github.com/trixi-framework/Trixi.jl/pull/2062.

### CODE REVIEW

**Review by ranocha — COMMENTED** [review]
I plan to merge your PR to Trixi.jl when @andrewwinters5000 agrees. Then, we can release the new version of Trixi.jl and you can update TrixiShallowWater.jl as required in this PR. Does that sound okay to you?

**Comment by patrickersing** [comment]
> I plan to merge your PR to Trixi.jl when @andrewwinters5000 agrees. Then, we can release the new version of Trixi.jl and you can update TrixiShallowWater.jl as required in this PR. Does that sound okay to you?

Yes, that sounds good to me :+1:

**Comment by ranocha** [comment]
The new version of Trixi.jl is released, so you can go ahead with this PR.

**Review by andrewwinters5000 — APPROVED** [review]
LGTM!

**Pull request merged**
